portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.hello, name="hello"),
    path('about_me/', views.about_me, name="about_me"),
    path('skills/', views.skills, name="skills"),
    path('experience/', views.experience, name="experience"),
    path('contact/', views.contact, name="contact"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render


def hello(request):
    return render(request, 'portfolio/pages/hello.html')


def about_me(request):
    return render(request, 'portfolio/pages/about_me.html')


def skills(request):
    return render(request, 'portfolio/pages/skills.html')


def experience(request):
    return render(request, 'portfolio/pages/experience.html')


def contact(request):
    return render(request, 'portfolio/pages/contact.html')

portfolio/templates/portfolio/pages/about_me.html
{% load static %}

{% include 'portfolio/partials/head.html' %}
    <title>Anna Maria | _about-me</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">
</head> 

<body>
    {% include 'portfolio/partials/nav.html' %}

    <p>About me</p>

    {% include 'portfolio/partials/footer.html' %}
</body>

</html> 

portfolio/templates/portfolio/pages/contact.html
{% load static %}

{% include 'portfolio/partials/head.html' %}
    <title>Anna Maria | _contact</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">
</head> 

<body>
    {% include 'portfolio/partials/nav.html' %}

    <p>Contact</p>

    {% include 'portfolio/partials/footer.html' %}
</body>

</html> 

portfolio/templates/portfolio/pages/experience.html
{% load static %}

{% include 'portfolio/partials/head.html' %}
    <title>Anna Maria | _experience</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">
</head> 

<body>
    {% include 'portfolio/partials/nav.html' %}

    <p>Experience</p>

    {% include 'portfolio/partials/footer.html' %}
</body>

</html> 

portfolio/templates/portfolio/pages/hello.html
{% load static %}

{% include 'portfolio/partials/head.html' %}
<title>Anna Maria | _hello</title>
<link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">
<link rel="stylesheet" href="{% static 'portfolio/css/hello.css' %}">
</head> 

<body>
    {% include 'portfolio/partials/nav.html' %}

    <div class="hello-page-container">
        <div class="hello-page-container-one">
            <div class="hello-wrapper-one">
                <p>Hi all. I am</p>
                <h1>Anna Maria</h1>
                <h2>> Full Stack Developer</h2>
            </div>
            <div class="hello-wrapper-two">
                <div id="dev">
                    <span># dev.py</span> 
                </div>
                <br>
                <span><span id="blue-green">dev</span> = {</span>
                <br>
                <span>&nbsp&nbsp&nbsp&nbsp"<span id="yellow">name</span>": "<span id="yellow">Anna Maria</span>",</span>
                <br>
                <span>&nbsp&nbsp&nbsp&nbsp"<span id="yellow">age</span>": <span id="purple">20,</span></span>
                <br>
                <span>&nbsp&nbsp&nbsp&nbsp"<span id="yellow">formation</span>": "<span id="yellow">Information system (2022-Present)</span>",</span>
                <br>
                <span>}</span>
                <br>
                <br>
                <span><span id="purple">print</span>(<span id="blue-green">dev</span>)</span>
            </div>
        </div>
        <div class="hello-page-container-two">
            <img id="blur" src="{% static 'portfolio/images/header-blur.png' %}" alt="">
            <img id="me" src="{% static 'portfolio/images/me.png' %}" alt="">
        </div>
    </div>

    {% include 'portfolio/partials/footer.html' %}
</body>

</html> 

portfolio/templates/portfolio/pages/skills.html
{% load static %}

{% include 'portfolio/partials/head.html' %}
    <title>Anna Maria | _skills</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">
</head> 

<body>
    {% include 'portfolio/partials/nav.html' %}

    <p>Skills</p>

    {% include 'portfolio/partials/footer.html' %}
</body>

</html> 

portfolio/templates/portfolio/partials/footer.html
{% load static %}

<footer>
    <div class="footer-container">
        <div class="footer-wrapper">
            <span id="footer-find">find me in:</span>
        </div>
        <div class="footer-wrapper">
            <a class="footer-icons" href="https://github.com/imnotannamaria" target="_blank"><img id="width-icon" src="{% static 'portfolio/images/git.svg' %}" alt=""></a>
        </div>
        <div class="footer-wrapper">
            <a  class="footer-icons" href="https://www.linkedin.com/in/imnotannamaria/" target="_blank"><img id="width-icon" src="{% static 'portfolio/images/linkedin.svg' %}" alt=""></a>
        </div>
        <div class="footer-wrapper">
            <a class="footer-icons"  href="mailto:aannamariabr@outlook.com?subject=Hello%20again" target="_blank"><img id="width-icon" src="{% static 'portfolio/images/email.svg' %}" alt=""></a>
        </div>
        <div class="footer-separetor">

        </div>
        <div class="footer-wrapper" id="footer-name">
            <span>@imnotannamaria</span>
        </div>
    </div>
</footer>

portfolio/templates/portfolio/partials/head.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap" rel="stylesheet"> 

portfolio/templates/portfolio/partials/nav.html
<nav>
    <div class="hello-container">
        {% comment %} <h1><a id="logo" href="{% url 'portfolio:hello'%}">anna-maria</a></h1> {% endcomment %}
        <a href="{% url 'portfolio:hello'%}"><h1>anna-maria</h1></a>

        <ul>
            <a href="{% url 'portfolio:hello'%}">
                <div class="hello-nav-wrapper" id="nav-hello">
                    <span>_hello</span>
                </div>
            </a>
            <a href="{% url 'portfolio:about_me'%}">
                <div class="hello-nav-wrapper" id="nav-aboutme">
                    <span>_about-me</span>
                </div>
            </a>
            <a href="{% url 'portfolio:skills'%}">
                <div class="hello-nav-wrapper" id="nav-skills">
                    <span>_skills</span>
                </div>
            </a>
            <a href="{% url 'portfolio:experience'%}">
                <div class="hello-nav-wrapper" id="nav-xp">
                    <span>_experience</span>
                </div>
            </a>
            <a href="{% url 'portfolio:contact'%}">
                <div class="hello-nav-wrapper" id="nav-contact">
                    <span>_contact</span>
                </div>
            </a>
        </ul>
    </div>
</nav>